name: s2p-lbm
channels:
  - defaults
  - conda-forge
dependencies:
  - mkl
  - numba
  - numpy
  - h5py=2.10.0
  - tbb
  - python[version='>=3.8,<3.9']
  - pip
  - scikit-learn
  - matplotlib
  - ipykernel
  - napari