name: s2p-lbm
channels:
  - defaults
  - conda-forge
dependencies:
  - python>=3.8,<3.9
  - pip
  - mkl
  - tbb
  - numpy
  - numba
  - napari
  - matplotlib
  - scikit-learn
  - mrcfile
  - mkl_fft
  - dask-image
  - pip: 
    - scipy>=1.4.0
    - torch>=1.7.1
    - natsort
    - rastermap>0.1.0
    - tifffile
    - scanimage-tiff-reader>=1.4.1
    - importlib-metadata
    - paramiko
    - pynwb
    - sbxreader
    - imreg-dft-nw
